create table notebook (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TEXT VARCHAR(50) NOT NULL,
LOCALDATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
STATUS VARCHAR(50) NOT NULL
--STATUS ENUM('HAS_NOT_STARTED', 'IN_PROGRESS', 'COMPLETED') NOT NULL DEFAULT 'HAS_NOT_STARTED'
);
